### ISSUE TITLE
how do you use this

### ISSUE THREAD

**Issue by ghost** [unixpickle/LibOrange#5]
i dont know how to run .m or .h files
i am on linux

**Comment by RSully** [comment]
This is written in [Objective-C](http://lmgtfy.com/?q=m+file+extension) to be used on OS X or iOS. It may run on Linux (e.g. GNUstep) but I assume that that is unsupported at best. For Linux, you may want to look at [libpurple](https://developer.pidgin.im/wiki/WhatIsLibpurple).

**Comment by ghost** [comment]
thanks for the help i might try with GNUstep and if that dosnt work i will
try libpurple
